services:
  postgres:
    container_name: postgres_mukund
    image: postgres
    environment:
      POSTGRES_USER: kakranmeenu73@gmail.com
      POSTGRES_PASSWORD: ^_^meenu
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: online_book_management
    volumes:
      - postgres:/data/postgres
    ports:
      - 1148:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025


networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local


